### ISSUE TITLE
backward() missing 1 required positional argument: 'optimizer_idx'

### ISSUE THREAD

**Issue by liketheflower** [thomasly/SubGNN#10]
when 
```
/SubGNN/SubGNN$ ./scripts/run_train_config.sh 
```
Got the following error
```
Epoch 0:   0%|                                                                                                                                              | 0/4 [00:00<?, ?it/s]
[W 2021-03-04 23:31:37,907] Trial 13 failed because of the following error: TypeError("backward() missing 1 required positional argument: 'optimizer_idx'")
Traceback (most recent call last):
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 211, in _run_trial
    value_or_values = func(trial)
  File "train_config.py", line 275, in <lambda>
    study.optimize(lambda trial: train_model(run_config, trial), n_trials=run_config['optuna']['opt_n_trials'], n_jobs =run_config['optuna']['opt_n_cores'])
  File "train_config.py", line 188, in train_model
    trainer.fit(model)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 513, in fit
    self.dispatch()
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in dispatch
    self.accelerator.start_training(self)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 111, in start_training
    self._results = trainer.run_train()
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 644, in run_train
    self.train_loop.run_training_epoch()
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 492, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 650, in run_training_batch
    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 434, in optimizer_step
    using_lbfgs=is_lbfgs,
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1384, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/core/optimizer.py", line 219, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/core/optimizer.py", line 135, in __optimizer_step
    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 278, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 283, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 160, in optimizer_step
    optimizer.step(closure=lambda_closure, **kwargs)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/torch/optim/adam.py", line 66, in step
    loss = closure()
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 645, in train_step_and_backward_closure
    split_batch, batch_idx, opt_idx, optimizer, self.trainer.hiddens
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 745, in training_step_and_backward
    self.backward(result, optimizer, opt_idx)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 775, in backward
    result.closure_loss, optimizer, opt_idx, should_accumulate, *args, **kwargs
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 258, in backward
    self.lightning_module, closure_loss, optimizer, optimizer_idx, should_accumulate, *args, **kwargs
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 71, in backward
    model.backward(closure_loss, optimizer, opt_idx)
TypeError: backward() missing 1 required positional argument: 'optimizer_idx'
Traceback (most recent call last):
  File "train_config.py", line 285, in <module>
    main()
  File "train_config.py", line 275, in main
    study.optimize(lambda trial: train_model(run_config, trial), n_trials=run_config['optuna']['opt_n_trials'], n_jobs =run_config['optuna']['opt_n_cores'])
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/study.py", line 385, in optimize
    show_progress_bar=show_progress_bar,
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 73, in _optimize
    progress_bar=progress_bar,
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 164, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 262, in _run_trial
    raise func_err
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 211, in _run_trial
    value_or_values = func(trial)
  File "train_config.py", line 275, in <lambda>
    study.optimize(lambda trial: train_model(run_config, trial), n_trials=run_config['optuna']['opt_n_trials'], n_jobs =run_config['optuna']['opt_n_cores'])
  File "train_config.py", line 188, in train_model
    trainer.fit(model)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 513, in fit
    self.dispatch()
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in dispatch
    self.accelerator.start_training(self)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 111, in start_training
    self._results = trainer.run_train()
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 644, in run_train
    self.train_loop.run_training_epoch()
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 492, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 650, in run_training_batch
    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 434, in optimizer_step
    using_lbfgs=is_lbfgs,
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1384, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/core/optimizer.py", line 219, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/core/optimizer.py", line 135, in __optimizer_step
    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 278, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 283, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 160, in optimizer_step
    optimizer.step(closure=lambda_closure, **kwargs)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/torch/optim/adam.py", line 66, in step
    loss = closure()
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 645, in train_step_and_backward_closure
    split_batch, batch_idx, opt_idx, optimizer, self.trainer.hiddens
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 745, in training_step_and_backward
    self.backward(result, optimizer, opt_idx)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 775, in backward
    result.closure_loss, optimizer, opt_idx, should_accumulate, *args, **kwargs
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 258, in backward
    self.lightning_module, closure_loss, optimizer, optimizer_idx, should_accumulate, *args, **kwargs
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 71, in backward
    model.backward(closure_loss, optimizer, opt_idx)
TypeError: backward() missing 1 required positional argument: 'optimizer_idx'
```

**Comment by liketheflower** [comment]
Downgrade the pytorch-lightning version to 0.7.1 can solve this problem
```
pip install pytorch-lightning==0.7.1
```
