### ISSUE TITLE
ValueError: CategoricalDistribution does not support dynamic value space when change batch_size default value

### ISSUE THREAD

**Issue by liketheflower** [thomasly/SubGNN#15]
When changing the batch_size default value from [thisline](https://github.com/thomasly/SubGNN/blob/6d5e072b74c5689e79b23f740aa68c53bd89db4a/SubGNN/config_files/density/density_config.json#L50)
to 
```
"batch_size" :{
            "type" : "suggest_categorical",
            //"args" : [[ 64, 128] ]
            "args" : [[ 64] ]
        },

```
Got the following error
```
Running 50 Trials of optuna
Logging to  /raid/home/public/SubGNN_data/tensorboard/S_metab_optuna
[I 2021-03-11 17:32:18,621] Using an existing study with name '/raid/home/public/SubGNN_data/tensorboard/S_metab_optuna' instead of creating a new one.
[W 2021-03-11 17:32:18,664] Trial 4 failed because of the following error: ValueError('CategoricalDistribution does not support dynamic value space.')
Traceback (most recent call last):
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 211, in _run_trial
    value_or_values = func(trial)
  File "train_config.py", line 275, in <lambda>
    study.optimize(lambda trial: train_model(run_config, trial), n_trials=run_config['optuna']['opt_n_trials'], n_jobs =run_config['optuna']['opt_n_cores'])
  File "train_config.py", line 170, in train_model
    model, hyperparameters = build_model(run_config, trial)
  File "train_config.py", line 93, in build_model
    hyperparameters = get_hyperparams_optuna(run_config, trial)
  File "train_config.py", line 84, in get_hyperparams_optuna
    hyp_optuna = {k:get_optuna_suggest(run_config["hyperparams_optuna"][k], k, trial) for k in dict(run_config["hyperparams_optuna"]).keys()}
  File "train_config.py", line 84, in <dictcomp>
    hyp_optuna = {k:get_optuna_suggest(run_config["hyperparams_optuna"][k], k, trial) for k in dict(run_config["hyperparams_optuna"]).keys()}
  File "train_config.py", line 72, in get_optuna_suggest
    return getattr(trial, module_name)(*args)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/trial/_trial.py", line 505, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/trial/_trial.py", line 721, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/storages/_cached_storage.py", line 243, in set_trial_param
    study_id, trial_id, param_name, param_value_internal, distribution
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/storages/_rdb/storage.py", line 827, in _check_and_set_param_distribution
    ).check_and_add(session)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/storages/_rdb/models.py", line 355, in check_and_add
    self._check_compatibility_with_previous_trial_param_distributions(session)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/storages/_rdb/models.py", line 374, in _check_compatibility_with_previous_trial_param_distributions
    distributions.json_to_distribution(self.distribution_json),
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/distributions.py", line 531, in check_distribution_compatibility
    CategoricalDistribution.__name__ + " does not support dynamic value space."
ValueError: CategoricalDistribution does not support dynamic value space.
Traceback (most recent call last):
  File "train_config.py", line 285, in <module>
    main()
  File "train_config.py", line 275, in main
    study.optimize(lambda trial: train_model(run_config, trial), n_trials=run_config['optuna']['opt_n_trials'], n_jobs =run_config['optuna']['opt_n_cores'])
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/study.py", line 385, in optimize
    show_progress_bar=show_progress_bar,
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 73, in _optimize
    progress_bar=progress_bar,
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 164, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 262, in _run_trial
    raise func_err
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 211, in _run_trial
    value_or_values = func(trial)
  File "train_config.py", line 275, in <lambda>
    study.optimize(lambda trial: train_model(run_config, trial), n_trials=run_config['optuna']['opt_n_trials'], n_jobs =run_config['optuna']['opt_n_cores'])
  File "train_config.py", line 170, in train_model
    model, hyperparameters = build_model(run_config, trial)
  File "train_config.py", line 93, in build_model
    hyperparameters = get_hyperparams_optuna(run_config, trial)
  File "train_config.py", line 84, in get_hyperparams_optuna
    hyp_optuna = {k:get_optuna_suggest(run_config["hyperparams_optuna"][k], k, trial) for k in dict(run_config["hyperparams_optuna"]).keys()}
  File "train_config.py", line 84, in <dictcomp>
    hyp_optuna = {k:get_optuna_suggest(run_config["hyperparams_optuna"][k], k, trial) for k in dict(run_config["hyperparams_optuna"]).keys()}
  File "train_config.py", line 72, in get_optuna_suggest
    return getattr(trial, module_name)(*args)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/trial/_trial.py", line 505, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/trial/_trial.py", line 721, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/storages/_cached_storage.py", line 243, in set_trial_param
    study_id, trial_id, param_name, param_value_internal, distribution
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/storages/_rdb/storage.py", line 827, in _check_and_set_param_distribution
    ).check_and_add(session)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/storages/_rdb/models.py", line 355, in check_and_add
    self._check_compatibility_with_previous_trial_param_distributions(session)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/storages/_rdb/models.py", line 374, in _check_compatibility_with_previous_trial_param_distributions
    distributions.json_to_distribution(self.distribution_json),
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/distributions.py", line 531, in check_distribution_compatibility
    CategoricalDistribution.__name__ + " does not support dynamic value space."
ValueError: CategoricalDistribution does not support dynamic value space.
```

**Comment by liketheflower** [comment]
We will see this error if you change a suggest_categorical and Optuna loads a previously saved study.
- How to fix:
Go to the previously saved location, delete or rename the saved study.
For example:
```
(subGemb_update) jimmyshen@dgx-station:/raid/home/public/SubGNN_data/tensorboard$ pwd
/raid/home/public/SubGNN_data/tensorboard
(subGemb_update) jimmyshen@dgx-station:/raid/home/public/SubGNN_data/tensorboard$ mv S_bace_optuna S_bace_optuna_old
(subGemb_update) jimmyshen@dgx-station:/raid/home/public/SubGNN_data/tensorboard$ ls
S_bace_optuna_old  S_metab_optuna  S_metab_optuna_old
```
The problem can be solved.
