### ISSUE TITLE
MemoryError: Unable to allocate 2.78 PiB for an array with shape (19793132, 19793132) and data type int64

### ISSUE THREAD

**Issue by thomasly** [thomasly/SubGNN#2]
This issue should be related to the large size of the ChemBL dataset and the lack of mini-batch when generating node embeddings.

Full error message as below:

Using device: cuda:0
Tesla V100-DGXS-16GB
Traceback (most recent call last):
  File "/raid/home/yangliu/miniconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/raid/home/yangliu/miniconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/raid/home/yangliu/slgnn/SubGNN/prepare_dataset/prepare_dataset.py", line 1033, in <module>
    main()
  File "/raid/home/yangliu/slgnn/SubGNN/prepare_dataset/prepare_dataset.py", line 1029, in main
    train_node_emb.generate_emb()
  File "/raid/home/yangliu/slgnn/SubGNN/prepare_dataset/train_node_emb.py", line 244, in generate_emb
    all_data = preprocess.read_graphs(str(config.DATASET_DIR / "edge_list.txt"))
  File "/raid/home/yangliu/slgnn/SubGNN/prepare_dataset/preprocess.py", line 40, in read_graphs
    feat_mat = np.eye(len(nx_G.nodes), dtype=int)
  File "/raid/home/yangliu/miniconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/twodim_base.py", line 199, in eye
    m = zeros((N, M), dtype=dtype, order=order)
MemoryError: Unable to allocate 2.78 PiB for an array with shape (19793132, 19793132) and data type int64

**Comment by thomasly** [comment]
The original node features are just a specific one-hot encoding for each node. Now I use atom features (atom type, degree, formal charge, hybridization type, aromatic, chirality) as node features. So we can skip the node embedding step.
