### ISSUE TITLE
Cannot import name 'GraphSAINTRandomWalkSampler' from 'torch_geometric.data'

### ISSUE THREAD

**Issue by liketheflower** [thomasly/SubGNN#6]
```
SubGNN/prepare_dataset$ python prepare_dataset.py 
Traceback (most recent call last):
  File "prepare_dataset.py", line 13, in <module>
    import train_node_emb
  File "/raid/home/jimmyshen/repos/SubGNN/prepare_dataset/train_node_emb.py", line 16, in <module>
    if config.MINIBATCH == "GraphSaint": from torch_geometric.data import GraphSAINTRandomWalkSampler
ImportError: cannot import name 'GraphSAINTRandomWalkSampler' from 'torch_geometric.data' (/home/XXX/anaconda3/envs/gnn/lib/python3.7/site-packages/torch_geometric/data/__init__.py)
```
Torch version: 1.4.0
torch_geometric version 
```
>>> torch_geometric.__version__
'1.4.3'
```
Should be the torch_geometric version is too low.

**Comment by liketheflower** [comment]
Upgrade the torch to version 1.7.1 and upgrade torch_geometric version, the code works
```
>>> torch_geometric.__version__
'1.6.3'
```
Script used to install torch_geometric
```
TORCH=1.7.1
CUDA=cu101
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html
pip install torch-geometric
```
