### ISSUE TITLE
Cannot set the device explicitly. Please use module.to(new_device).

### ISSUE THREAD

**Issue by liketheflower** [thomasly/SubGNN#8]
Got the following error when run
```
python train_config.py -config_path config_files/hpo_metab/metab_config.json
```

```
Running 50 Trials of optuna
Logging to  /raid/home/public/JIMMY/SubGNN_data/tensorboard/S_metab_optuna
[I 2021-03-04 22:54:59,994] Using an existing study with name '/raid/home/public/JIMMY/SubGNN_data/tensorboard/S_metab_optuna' instead of creating a new one.
[W 2021-03-04 22:55:00,131] Trial 1 failed because of the following error: RuntimeError('Cannot set the device explicitly. Please use module.to(new_device).')
Traceback (most recent call last):
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 211, in _run_trial
    value_or_values = func(trial)
  File "train_config.py", line 273, in <lambda>
    study.optimize(lambda trial: train_model(run_config, trial), n_trials=run_config['optuna']['opt_n_trials'], n_jobs =run_config['optuna']['opt_n_cores'])
  File "train_config.py", line 168, in train_model
    model, hyperparameters = build_model(run_config, trial)
  File "train_config.py", line 106, in build_model
    run_config["similarities_path"], run_config["shortest_paths_path"], run_config['degree_sequence_path'], run_config['ego_graph_path'])
  File "/raid/home/jimmyshen/repos/SubGNN/SubGNN/SubGNN.py", line 99, in __init__
    self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/torch/nn/modules/module.py", line 826, in __setattr__
    object.__setattr__(self, name, value)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 53, in device
    raise RuntimeError('Cannot set the device explicitly. Please use module.to(new_device).')
RuntimeError: Cannot set the device explicitly. Please use module.to(new_device).
Traceback (most recent call last):
  File "train_config.py", line 283, in <module>
    main()
  File "train_config.py", line 273, in main
    study.optimize(lambda trial: train_model(run_config, trial), n_trials=run_config['optuna']['opt_n_trials'], n_jobs =run_config['optuna']['opt_n_cores'])
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/study.py", line 385, in optimize
    show_progress_bar=show_progress_bar,
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 73, in _optimize
    progress_bar=progress_bar,
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 164, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 262, in _run_trial
    raise func_err
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 211, in _run_trial
    value_or_values = func(trial)
  File "train_config.py", line 273, in <lambda>
    study.optimize(lambda trial: train_model(run_config, trial), n_trials=run_config['optuna']['opt_n_trials'], n_jobs =run_config['optuna']['opt_n_cores'])
  File "train_config.py", line 168, in train_model
    model, hyperparameters = build_model(run_config, trial)
  File "train_config.py", line 106, in build_model
    run_config["similarities_path"], run_config["shortest_paths_path"], run_config['degree_sequence_path'], run_config['ego_graph_path'])
  File "/raid/home/jimmyshen/repos/SubGNN/SubGNN/SubGNN.py", line 99, in __init__
    self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/torch/nn/modules/module.py", line 826, in __setattr__
    object.__setattr__(self, name, value)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 53, in device
    raise RuntimeError('Cannot set the device explicitly. Please use module.to(new_device).')
RuntimeError: Cannot set the device explicitly. Please use module.to(new_device).
```
Not clear about the reason yet.

**Comment by liketheflower** [comment]
Comment line 99 of  SubGNN.py  can solve the problem temporarily.
