### ISSUE TITLE
__init__() got an unexpected keyword argument 'filepath'

### ISSUE THREAD

**Issue by liketheflower** [thomasly/SubGNN#9]
Should be related to the version of pytorch_lightning. The version I am using is '1.2.1'. The original version the SubGNN author used is 0.7
```
[I 2021-03-04 23:22:34,735] Using an existing study with name '/raid/home/public/JIMMY/SubGNN_data/tensorboard/S_metab_optuna' instead of creating a new one.
--- Finished reading in data ---
/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/torch/nn/modules/rnn.py:61: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.01821903938832552 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
Tensorboard logging at  /raid/home/public/JIMMY/SubGNN_data/tensorboard/S_metab_optuna/version_1034384
[W 2021-03-04 23:22:35,011] Trial 10 failed because of the following error: TypeError("__init__() got an unexpected keyword argument 'filepath'")
Traceback (most recent call last):
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 211, in _run_trial
    value_or_values = func(trial)
  File "train_config.py", line 273, in <lambda>
    study.optimize(lambda trial: train_model(run_config, trial), n_trials=run_config['optuna']['opt_n_trials'], n_jobs =run_config['optuna']['opt_n_cores'])
  File "train_config.py", line 171, in train_model
    trainer, trainer_kwargs, results_path = build_trainer(run_config, hyperparameters, trial)
  File "train_config.py", line 149, in build_trainer
    mode='max'
TypeError: __init__() got an unexpected keyword argument 'filepath'
Traceback (most recent call last):
  File "train_config.py", line 283, in <module>
    main()
  File "train_config.py", line 273, in main
    study.optimize(lambda trial: train_model(run_config, trial), n_trials=run_config['optuna']['opt_n_trials'], n_jobs =run_config['optuna']['opt_n_cores'])
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/study.py", line 385, in optimize
    show_progress_bar=show_progress_bar,
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 73, in _optimize
    progress_bar=progress_bar,
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 164, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 262, in _run_trial
    raise func_err
  File "/home/jimmyshen/anaconda3/envs/subGemb_update/lib/python3.7/site-packages/optuna/_optimize.py", line 211, in _run_trial
    value_or_values = func(trial)
  File "train_config.py", line 273, in <lambda>
    study.optimize(lambda trial: train_model(run_config, trial), n_trials=run_config['optuna']['opt_n_trials'], n_jobs =run_config['optuna']['opt_n_cores'])
  File "train_config.py", line 171, in train_model
    trainer, trainer_kwargs, results_path = build_trainer(run_config, hyperparameters, trial)
  File "train_config.py", line 149, in build_trainer
    mode='max'
TypeError: __init__() got an unexpected keyword argument 'filepath'
```

**Comment by liketheflower** [comment]
See the [source code](https://github.com/PyTorchLightning/pytorch-lightning/blob/ec8d46e02b45ee6cd5713bd72b2ee7e2474c7ac1/pytorch_lightning/callbacks/model_checkpoint.py#L148), the api is changed.

**Comment by liketheflower** [comment]
Downgrade the version to 0.7.1 works
```
pip install pytorch-lightning==0.7.1
```
